### ISSUE TITLE
sugestão: add efeito reverb/slowed

### ISSUE THREAD

**Issue by Registradorold** [zRitsu/MuseHeart-MusicBot#13]
poderia adicionar o efeito reverb slowed ?

**Comment by zRitsu** [comment]
Boa parte desses filtros que tem por aí são focados pra uso no ffmpeg, atualmente o lavalink tem suporte pra slowed mas acho que reverb ainda não é possível.

quanto a possibilidade atual, to trabalhando no comando pra isso.
