### ISSUE TITLE
Suporte!

### ISSUE THREAD

**Issue by Anon5698** [zRitsu/MuseHeart-MusicBot#29]
Boa Noite, Tudo Bem? tive o seguindo problema na execução do bash no linux e não sei o que houve; já li os arquivos e tentei solucionar os erros de execução mais não consegui obter sucesso. Eu ultilizo Linux Ubuntu 20.04LTE e assim que inseri a chave do mongo db no .env como foi pedido para que eu migrasse meu projeto para minha máquina ao invés do Repl.it, ocorre esse erro ao rodar o comando: bash start.sh (procurei o run.sh, como pedido mais vi que esse é o que solicita o .env após a atualização do código na versão 1.18 se não me engano). Segue o erro da execução:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    pool.setup()
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/utils/client.py", line 195, in setup
    self.mongo_database = MongoDatabase(mongo_key)
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/utils/db.py", line 192, in __init__
    self._connect = AsyncIOMotorClient(token.strip("<>"), connectTimeoutMS=30000)
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/venv/lib/python3.8/site-packages/motor/core.py", line 148, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/venv/lib/python3.8/site-packages/pymongo/uri_parser.py", line 516, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "/home/anon5698/Downloads/Discord-Music-Bot-PT-BR/venv/lib/python3.8/site-packages/pymongo/uri_parser.py", line 71, in parse_userinfo
    raise InvalidURI(
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus
kill: uso: kill [-s SIGSPEC | -n SIGNUM | -SIGSPEC] PID | ESPEC-JOB ... ou kill -l [SIGSPEC]

OBS: Conto com sua ajuda, e espero que futuramente o bot seja compátivel também com Clouds como: SquareCloud e DisCloud.

**Comment by zRitsu** [comment]
o link do pymongo usado no .env ta com erro, tenta dar uma revisada nele (lembrando que a senha no link não deve ter os caracteres <> ) 

Sobre as clouds, o code funciona nelas sem problema.

**Comment by Anon5698** [comment]
Beleza, vou tentar resetar a senha e tentar rodar novamente. Sabe se após rodar ele no VSC do LInux eu posso enviar ele pra Discloud por exemplo? Porque não quero depender da Uptimerobot. Vi uns cara falando que pra mandar pra nuvem ele não pode requerir o: express(no caso do javascrypt e nem o .env porque pra java no caso usa o config.json), e o bot em questão, tem algum arquivo que não deva ser zipado na hora de enviar para essas plataformas?

**Comment by Anon5698** [comment]
Consegui rodar, agora só tenho que lembrar coo para o bash kkk, mais ainda gostaria de saber: Se após rodar ele no VSC do LInux eu posso enviar ele pra Discloud por exemplo? Porque não quero depender da Uptimerobot. Vi uns cara falando que pra mandar pra nuvem ele não pode requerir o: express(no caso do javascrypt e nem o .env porque pra java no caso usa o config.json), e o bot em questão, tem algum arquivo que não deva ser zipado na hora de enviar para essas plataformas?

**Comment by zRitsu** [comment]
tenho guia em video de como usar o bot em ambas

https://www.youtube.com/watch?v=79pLlrAETc4

https://www.youtube.com/watch?v=G1I6ZMIBgas

**Comment by zRitsu** [comment]
caso queira desativar o servidor interno (que gera o html + rpc websocket) no .env tem uma config com nome RUN_RPC_SERVER (deixa o valor dele como false)

**Comment by Anon5698** [comment]
> caso queira desativar o servidor interno (que gera o html + rpc websocket) no .env tem uma config com nome RUN_RPC_SERVER (deixa o valor dele como false)

Blz, vlw

**Comment by Anon5698** [comment]
> tenho guia em video de como usar o bot em ambas
> 
> https://www.youtube.com/watch?v=79pLlrAETc4
> 
> https://www.youtube.com/watch?v=G1I6ZMIBgas

Verei depois, vlw.

**Comment by Anon5698** [comment]
MANO! preciso de outra ajuda urgente, destivei os arquivos que rodavam meu bot no repl.it porque tinha conseguido rodar no bash do linux, porém ao tentar fazer um: `@client.event: 
                                                                   async def on_ready(): 
                                                                          print(client.guilds) 
                                                                          print("+--------------------------------+")
                                                                          print("BOT IS AVAILABLE NOW!")
                                                                          print("----------------------------------+)"`  , no arquivo main.py, ele agora me retorna o a mensagem para verificar o bot ativo como antes porém logo abaixo vem o seguinte erro: Iniciando bot (Verifique se o mesmo está online)...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from utils.client import BotPool
ImportError: No module named utils.client, E NÃO ME PERMITE LIGAR O BOT MESMO APAGANDO O CLIENT.EVENT, E EU JÁ TER TENTADO INSTALAR ESSE MODULO/MÉTODO  e ele não roda mesmo apagando o main.py e colocando o seu na pasta. Poderia me ajudar?

**Comment by Anon5698** [comment]
> caso queira desativar o servidor interno (que gera o html + rpc websocket) no .env tem uma config com nome RUN_RPC_SERVER (deixa o valor dele como false)

já está.

**Comment by zRitsu** [comment]
> MANO! preciso de outra ajuda urgente, destivei os arquivos que rodavam meu bot no repl.it porque tinha conseguido rodar no bash do linux, porém ao tentar fazer um: `@client.event: async def on_ready(): print(client.guilds) print("+--------------------------------+") print("BOT IS AVAILABLE NOW!") print("----------------------------------+)"` , no arquivo main.py, ele agora me retorna o a mensagem para verificar o bot ativo como antes porém logo abaixo vem o seguinte erro: Iniciando bot (Verifique se o mesmo está online)... Traceback (most recent call last): File "main.py", line 4, in from utils.client import BotPool ImportError: No module named utils.client, E NÃO ME PERMITE LIGAR O BOT MESMO APAGANDO O CLIENT.EVENT, E EU JÁ TER TENTADO INSTALAR ESSE MODULO/MÉTODO e ele não roda mesmo apagando o main.py e colocando o seu na pasta. Poderia me ajudar?

a pasta utils não foi localizada no mesmo diretorio do main.py

**Comment by Anon5698** [comment]
> > MANO! preciso de outra ajuda urgente, destivei os arquivos que rodavam meu bot no repl.it porque tinha conseguido rodar no bash do linux, porém ao tentar fazer um: `@client.event: async def on_ready(): print(client.guilds) print("+--------------------------------+") print("BOT IS AVAILABLE NOW!") print("----------------------------------+)"` , no arquivo main.py, ele agora me retorna o a mensagem para verificar o bot ativo como antes porém logo abaixo vem o seguinte erro: Iniciando bot (Verifique se o mesmo está online)... Traceback (most recent call last): File "main.py", line 4, in from utils.client import BotPool ImportError: No module named utils.client, E NÃO ME PERMITE LIGAR O BOT MESMO APAGANDO O CLIENT.EVENT, E EU JÁ TER TENTADO INSTALAR ESSE MODULO/MÉTODO e ele não roda mesmo apagando o main.py e colocando o seu na pasta. Poderia me ajudar?
> 
> a pasta utils não foi localizada no mesmo diretorio do main.py

Boa Tarde! E como movo ela ou crio ela lá? porque já tentei readicionar,mover,recriar e essas coisas mais tudo sem sucesso e não sei como sumiu se até a penultima execução do bot ela estava lá e rodando kkk

**Comment by zRitsu** [comment]
> > > MANO! preciso de outra ajuda urgente, destivei os arquivos que rodavam meu bot no repl.it porque tinha conseguido rodar no bash do linux, porém ao tentar fazer um: `@client.event: async def on_ready(): print(client.guilds) print("+--------------------------------+") print("BOT IS AVAILABLE NOW!") print("----------------------------------+)"` , no arquivo main.py, ele agora me retorna o a mensagem para verificar o bot ativo como antes porém logo abaixo vem o seguinte erro: Iniciando bot (Verifique se o mesmo está online)... Traceback (most recent call last): File "main.py", line 4, in from utils.client import BotPool ImportError: No module named utils.client, E NÃO ME PERMITE LIGAR O BOT MESMO APAGANDO O CLIENT.EVENT, E EU JÁ TER TENTADO INSTALAR ESSE MODULO/MÉTODO e ele não roda mesmo apagando o main.py e colocando o seu na pasta. Poderia me ajudar?
> > 
> > 
> > a pasta utils não foi localizada no mesmo diretorio do main.py
> 
> Boa Tarde! E como movo ela ou crio ela lá? porque já tentei readicionar,mover,recriar e essas coisas mais tudo sem sucesso e não sei como sumiu se até a penultima execução do bot ela estava lá e rodando kkk

se pissível manda print exibindo os arquivos que ta na pasta do bot (mesma pasta no qual ta sendo usado o start.sh)

**Comment by Anon5698** [comment]
Segue em anexo o Print!
![PRINT-BOT_DC](https://github.com/zRitsu/disnake-LL-music-bot/assets/36265813/d972c919-8989-41d6-98b2-57d3a07e8db9)

**Comment by zRitsu** [comment]
> 

abre o terminal (nessa mesma pasta) e tenta ligar o bot usando esse comando:
```bash
source venv/bin/activate && python3 main.py
```

**Comment by Anon5698** [comment]
> ```shell
> source venv/bin/activate && python3 main.py
> ```

Não funcionou mano, ainda dá o mesmo erro: `anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ source venv/bin/activate && python3 main.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from utils.client import BotPool
ModuleNotFoundError: No module named 'utils.client'
(venv) anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ `

**Comment by zRitsu** [comment]
confere a versão do python instalado na tua máquina (requer 3.8 ou superior) 
```bash
python3 --version
```

**Comment by Anon5698** [comment]
> confere a versão do python instalado na tua máquina (requer 3.8 ou superior)
> 
> ```shell
> python3 --version
> ```

mals, to atualizando o repositório dele kkkk ele tava na 2.7.18. Assim que atualizar eu vou rodar o bot e te aviso kkk

**Comment by Anon5698** [comment]
> 

ele tá na 3! Segue o terminal: `anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ python3 --version
Python 3.8.10
anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ python --version
Python 2.7.18
anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ 
`

**Comment by zRitsu** [comment]
usa esse comando 
```
pythn3 -m venv venv
source venv/bin/activate
python3 -m pip install -U -r requirements.txt
```

manda print do resultado e depois tenta ligar o bot com: 
```
source venv/bin/activate && python3 main.py
```

**Comment by Anon5698** [comment]
> usa esse comando
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> python3 -m pip install -U -r requirements.txt
> ```
> 
> manda print do resultado e depois tenta ligar o bot com:
> 
> ```
> source venv/bin/activate && python3 main.py
> ```

Segue outro erro, kkk tá dificil fazer esse código rodar de novo. Acho que vou rebaixar ele no seu repositório e recolocar as chaves no env sem alterar nada além dos arquivos do Repl.it porque mds! kkkk Print do Bash: `(venv) anon5698@AnONyMoUs:~/Downloads/SGZN_PRODUCTIONS(OFC)$ source venv/bin/activate && python3 main.py
Baixando lista de servidores lavalink (arquivo: lavalink.ini)
Commit ver: 08b597e9cb80500b01e70ab46473b728f64f2c3e
------------------------------
================================================
[OK] SGZN#2659 - error_handler.py Carregado.
================================================
[OK] SGZN#2659 - player_resume.py Carregado.
================================================
[OK] SGZN#2659 - fav_manager.py Carregado.
================================================
[OK] SGZN#2659 - server_manager.py Carregado.
================================================
[OK] SGZN#2659 - music_settings.py Carregado.
================================================
[OK] SGZN#2659 - skin_editor.py Carregado.
================================================
[OK] SGZN#2659 - guild_fav_manager.py Carregado.
================================================
[ERRO] SGZN#2659 - Falha ao carregar/recarregar o módulo: music
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/utils/client.py", line 883, in load_modules
    self.reload_extension(module_filename)
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/venv/lib/python3.8/site-packages/disnake/ext/commands/common_bot_base.py", line 601, in reload_extension
    raise errors.ExtensionNotLoaded(name)
disnake.ext.commands.errors.ExtensionNotLoaded: Extension 'modules.music' has not been loaded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/venv/lib/python3.8/site-packages/disnake/ext/commands/common_bot_base.py", line 451, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/modules/music.py", line 33, in <module>
    class Music(commands.Cog):
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/modules/music.py", line 601, in Music
    play_flags = argparse.ArgumentParser(exit_on_error=False)
TypeError: __init__() got an unexpected keyword argument 'exit_on_error'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/venv/lib/python3.8/site-packages/disnake/client.py", line 703, in _run_event
    await coro(*args, **kwargs)
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/utils/client.py", line 322, in on_ready
    bot.load_modules()
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/utils/client.py", line 893, in load_modules
    raise e
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/utils/client.py", line 888, in load_modules
    self.load_extension(module_filename)
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/venv/lib/python3.8/site-packages/disnake/ext/commands/common_bot_base.py", line 522, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/anon5698/Downloads/SGZN_PRODUCTIONS(OFC)/venv/lib/python3.8/site-packages/disnake/ext/commands/common_bot_base.py", line 454, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
disnake.ext.commands.errors.ExtensionFailed: Extension 'modules.music' raised an error: TypeError: __init__() got an unexpected keyword argument 'exit_on_error'`

**Comment by zRitsu** [comment]
o music.py foi editado? pois de alguma forma o ArgumentParser passou a ser class int...

por via das duvidas use o quick_update.sh pra atualizar/restaurar o code original

**Comment by Anon5698** [comment]
> o music.py foi editado? pois de alguma forma o ArgumentParser passou a ser class int...
> 
> por via das duvidas use o quick_update.sh pra atualizar/restaurar o code original

blz vou tentar...

**Comment by Anon5698** [comment]
> Deu certo! Rodei aqui.

Aproveitando o Ensejo: Nas próximas versões pode fazer um arquivo para o bot avisar quando está on-line e off-line no canal de avisos do servidor?

**Comment by Anon5698** [comment]
Boa Noite mano, surgiu outro problema... Antigamente eu rodava ele, ele abria na hora e agora ele liga mais quando tento rodar ele diz que ainda tá lligando e tenho que esperar porém esperei mais de 10 minutos e ele não rodou pelo pc(nativamente), mais pelo replit ele roda na hora. Segue o Print
![error](https://github.com/zRitsu/disnake-LL-music-bot/assets/36265813/643280a6-e806-46d5-99e9-90a85c268572)

**Comment by zRitsu** [comment]
ta iniciando o bot via comando? verifica se da algum erro no terminal

**Comment by Anon5698** [comment]
> ta iniciando o bot via comando? verifica se da algum erro no terminal

Ele não apresenta erro, inicia, conecta na call mudo e depois permite que eu pare ele no terminal com o: ctrl+z!

![error](https://github.com/zRitsu/disnake-LL-music-bot/assets/36265813/9fabc885-1c35-4dc2-9d81-6b61990108dc)
![error2](https://github.com/zRitsu/disnake-LL-music-bot/assets/36265813/825a83a2-6905-4055-81e5-45877d6406d9)

**Comment by zRitsu** [comment]
pode ser problema no servidor de música Derpy, vai no env e muda o AUTO_DOWNLOAD_LAVALINK_SERVERLIST pra false (isso vai fazer o code iniciar um lavalink server localmente ao ligar o bot)

**Comment by Anon5698** [comment]
> pode ser problema no servidor de música Derpy, vai no env e muda o AUTO_DOWNLOAD_LAVALINK_SERVERLIST pra false (isso vai fazer o code iniciar um lavalink server localmente ao ligar o bot)

Fiz isso e não mudou nada, ele instalou um pacote: jabba e mesmo assim não tocou nada kkk. Não sei mais onde pode ser esse problema. O engraçado é que parou do nada, atém ontem ele rodava de boa pelo pc e nem pedia atualização do kernel para rodar o: source e nem dava esses erros de entrar na call ficar mudo e depois sair e não rodar nada.

**Comment by zRitsu** [comment]
testa via navegador

**Comment by zRitsu** [comment]
testei o servidor publico mais cedo (derpy) e funcionou normal aqui...

**Comment by Anon5698** [comment]
> testa via navegador

Pelo navegador ele roda, inclusive no replit! Vou fazer o seguinte já que instalei tudo isso. Vou apagar a parta do projeto e rebaixar ela e auterar apenas o .env e vê se ele volta se não terei que usar apenas no Repl.it até a nova versão dele kkk

**Comment by Anon5698** [comment]
Boa Noite mano(a), tudo bem? Sigo com o problema acima e ainda não consegui solucionar, poderia me dar mais esse help? Desde já peço perdão pelo incomodo! Se não for pedir muito poderia me passar outra forma de contato(whatsapp,telegram, e etc), visto que entro pouco no git como deve ter notado e por essa razão creio que seria mais vantajoso a ambos pois percebo que também enra pouco aqui devido a suas particularidades. Ps: Estou no agurado de seu retorno. ;)

**Comment by LIKEaBORZ** [comment]
Olá, Obrigado por fazer esse trabalho, nós realmente apreciamos isso, Você poderia me dizer como desabilitar a atualização automática!

**Comment by LIKEaBORZ** [comment]
além de como desativar os comandos !up !update ou limitá-los para que apenas o proprietário do bot possa usá-los!
MUITO OBRIGADO, VOCÊ É O MELHOR!👍🏻👍🏻👍🏻👍🏻

**Comment by Anon5698** [comment]
> Olá, Obrigado por fazer esse trabalho, nós realmente apreciamos isso, Você poderia me dizer como desabilitar a atualização automática!

Desculpe, poderia reformular? Não entendi sua dúvida.

**Comment by Anon5698** [comment]
> além de como desativar os comandos !up !update ou limitá-los para que apenas o proprietário do bot possa usá-los! MUITO OBRIGADO, VOCÊ É O MELHOR!👍🏻👍🏻👍🏻👍🏻

Nas configurações do bot há campos onde pode fazer essas modificações, porém eu preferi deixar o repositório atual para atualizar automaticamente.

**Comment by Anon5698** [comment]
Boa noite zRitsu ! Tudo bem? Espero que sim... Gostaria de saber se é possível criar um código mais light(menos pesado desse bot), visto que não quero parar de usar-lo... Porém recentemente tenho tido problemas de conexão com seus servidores ou time-out de funções como: play e play_music_file. Ele fica pensandopor mais de 10 minutos e depois diz que o tempo de resposta excedeu ou que o servidor: albinhakanson retornou a resposta(NONE), e não reproduz as músicas. Gostaria de saber se está fazendo manuntenção ou algo do tipo para ele estar ocilando tanto... Me responda assim que possível porfavor.

**Comment by zRitsu** [comment]
> Boa noite zRitsu ! Tudo bem? Espero que sim... Gostaria de saber se é possível criar um código mais light(menos pesado desse bot), visto que não quero parar de usar-lo... Porém recentemente tenho tido problemas de conexão com seus servidores ou time-out de funções como: play e play_music_file. Ele fica pensandopor mais de 10 minutos e depois diz que o tempo de resposta excedeu ou que o servidor: albinhakanson retornou a resposta(NONE), e não reproduz as músicas. Gostaria de saber se está fazendo manuntenção ou algo do tipo para ele estar ocilando tanto... Me responda assim que possível porfavor.

Esse problema não é com o code de música em em si mas com os servidores públicos, alguns podem apresentar instabilidade e até mesmo delays e lags. pra corrigir isso teria que habilitar a execução do lavalink LOCAL mas dependendo de onde tiver hospedando o bot pode não ter recursos suficiente ou a execução do Lavalink.jar ser bloqueado (vi isso acontecer em algumas hospedagens que fornecem planos gratuitos que usam painel pterodactyl)

no caso da squarecloud e discloud recomendo o plano que forneça 1vcpu (cerca de 11 a 14 reais)  e ela vem com 2gb de ram (embora o minimo seja 1gb)

**Comment by Anon5698** [comment]
> > Boa noite zRitsu ! Tudo bem? Espero que sim... Gostaria de saber se é possível criar um código mais light(menos pesado desse bot), visto que não quero parar de usar-lo... Porém recentemente tenho tido problemas de conexão com seus servidores ou time-out de funções como: play e play_music_file. Ele fica pensandopor mais de 10 minutos e depois diz que o tempo de resposta excedeu ou que o servidor: albinhakanson retornou a resposta(NONE), e não reproduz as músicas. Gostaria de saber se está fazendo manuntenção ou algo do tipo para ele estar ocilando tanto... Me responda assim que possível porfavor.
> 
> Esse problema não é com o code de música em em si mas com os servidores públicos, alguns podem apresentar instabilidade e até mesmo delays e lags. pra corrigir isso teria que habilitar a execução do lavalink LOCAL mas dependendo de onde tiver hospedando o bot, pode não ter recursos suficiente ou a execução do Lavalink.jar ser bloqueado (vi isso acontecer em algumas hospedagens que fornecem planos gratuitos que usam painel pterodactyl)
> 
> no caso da squarecloud e discloud recomendo o plano que forneça no mínimo 1vcpu (cerca de 11 a 14 reais) e ela vem com 2gb de ram (embora o minimo seja 1gb)

Entendi, obrigado por responder, eu o hospedava em uma empresa que usa o Pterodactyl mesmo, porém eles estão migrando o portal,site de vendas e hospedagem ai tentei usar pelo replit, e para minha surpresa anteontem ele funcionou nas primeiras horas dps ao mudar ele de call começou a dar delay no comando play, e depois ele retornava o erro de: NONE no servidor que lhe falei. Mas com os demais comandos ele até respondia tranquilo. Observei que era mais no play e play_music_file. A propósito, você possui discord ou whatsapp? Eu quase não entro no git/github como pode perceber hehe, então se tiver porfavor peço que me envie para poder-mos manter um contato de forma mais eficaz tudo bem?

**Comment by zRitsu** [comment]
@Anon5698 Não confio muito passar contado de zap com receio de vazar meu número mas tem um server do dc: https://discord.gg/NpVnNHE9s9

Sobre o erro foi feito alguns updates no code pra lidar com problemas especificos como Read Timeout etc, mas o erro 403 do youtube a correção tem que ser feita nos servidores públicos. Caso esteja usando o servidor LOCAL basta apenas deletar o lavalink.jar e as pastas plugins + .java ou .jabba (caso tenha elas) e ligar o bot novamente

**Comment by zRitsu** [comment]
Fechando essa issue, caso tenha algum problema relacionado a issue atual você pode reabrir ou criar uma nova issue caso o problema seja outro.
