### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by BarboPT** [zRitsu/MuseHeart-MusicBot#30]
================================================
Application command synchronization:
GLOBAL COMMANDS
===============
| Update is required: False
| To upsert:
|     -
| To edit:
|     -
| To delete:
|     -
| No changes:
|     <SlashCommand name='fav'>
|     <SlashCommand name='server_playlist'>
|     <SlashCommand name='integration'>
|     <SlashCommand name='about'>
|     <SlashCommand name='invite'>
|     <SlashCommand name='stage_announce'>
|     <SlashCommand name='search'>
|     <SlashCommand name='connect'>
|     <SlashCommand name='play_music_file'>
|     <SlashCommand name='play'>
|     <SlashCommand name='skipto'>
|     <SlashCommand name='skip'>
|     <SlashCommand name='back'>
|     <SlashCommand name='voteskip'>
|     <SlashCommand name='volume'>
|     <SlashCommand name='pause'>
|     <SlashCommand name='resume'>
|     <SlashCommand name='seek'>
|     <SlashCommand name='loop_mode'>
|     <SlashCommand name='loop_amount'>
|     <SlashCommand name='remove'>
|     <SlashCommand name='readd_songs'>
|     <SlashCommand name='move'>
|     <SlashCommand name='rotate'>
|     <SlashCommand name='song_request_thread'>
|     <SlashCommand name='nightcore'>
|     <SlashCommand name='controller'>
|     <SlashCommand name='add_dj'>
|     <SlashCommand name='remove_dj'>
|     <SlashCommand name='stop'>
|     <SlashCommand name='queue'>
|     <SlashCommand name='clear_queue'>
|     <SlashCommand name='restrict_mode'>
|     <SlashCommand name='247'>
|     <SlashCommand name='change_node'>
|     <SlashCommand name='player_settings'>
|     <SlashCommand name='setup'>
|     <SlashCommand name='reset'>
|     <SlashCommand name='add_dj_role'>
|     <SlashCommand name='remove_dj_role'>
|     <SlashCommand name='change_skin'>
|     <SlashCommand name='nodeinfo'>
|     <SlashCommand name='rich_presence'>
|     <UserCommand name='avatar'>
|     <UserCommand name='Add DJ'>
|     <MessageCommand name='add to queue'>

**Comment by BarboPT** [comment]
================================================
Application command synchronization:
GLOBAL COMMANDS
===============
| Update is required: False
| To upsert:
|     -
| To edit:
|     -
| To delete:
|     -
| No changes:
|     <SlashCommand name='fav'>
|     <SlashCommand name='server_playlist'>
|     <SlashCommand name='integration'>
|     <SlashCommand name='about'>
|     <SlashCommand name='invite'>
|     <SlashCommand name='stage_announce'>
|     <SlashCommand name='search'>
|     <SlashCommand name='connect'>
|     <SlashCommand name='play_music_file'>
|     <SlashCommand name='play'>
|     <SlashCommand name='skipto'>
|     <SlashCommand name='skip'>
|     <SlashCommand name='back'>
|     <SlashCommand name='voteskip'>
|     <SlashCommand name='volume'>
|     <SlashCommand name='pause'>
|     <SlashCommand name='resume'>
|     <SlashCommand name='seek'>
|     <SlashCommand name='loop_mode'>
|     <SlashCommand name='loop_amount'>
|     <SlashCommand name='remove'>
|     <SlashCommand name='readd_songs'>
|     <SlashCommand name='move'>
|     <SlashCommand name='rotate'>
|     <SlashCommand name='song_request_thread'>
|     <SlashCommand name='nightcore'>
|     <SlashCommand name='controller'>
|     <SlashCommand name='add_dj'>
|     <SlashCommand name='remove_dj'>
|     <SlashCommand name='stop'>
|     <SlashCommand name='queue'>
|     <SlashCommand name='clear_queue'>
|     <SlashCommand name='restrict_mode'>
|     <SlashCommand name='247'>
|     <SlashCommand name='change_node'>
|     <SlashCommand name='player_settings'>
|     <SlashCommand name='setup'>
|     <SlashCommand name='reset'>
|     <SlashCommand name='add_dj_role'>
|     <SlashCommand name='remove_dj_role'>
|     <SlashCommand name='change_skin'>
|     <SlashCommand name='nodeinfo'>
|     <SlashCommand name='rich_presence'>
|     <UserCommand name='avatar'>
|     <UserCommand name='Add DJ'>
|     <MessageCommand name='add to queue'>

**Comment by BarboPT** [comment]
Application command synchronization:
GLOBAL COMMANDS

Update is required: False
No changes:
  <SlashCommand name='fav'>
  <SlashCommand name='server_playlist'>
   <SlashCommand name='integration'>
    <SlashCommand name='about'>
   <SlashCommand name='invite'>
<SlashCommand name='stage_announce'>
    <SlashCommand name='search'>
    <SlashCommand name='connect'>
     <SlashCommand name='play_music_file'>
  <SlashCommand name='play'>
    <SlashCommand name='skipto'>
     <SlashCommand name='skip'>
   <SlashCommand name='back'>
    <SlashCommand name='voteskip'>
    <SlashCommand name='volume'>
  <SlashCommand name='pause'>
    <SlashCommand name='resume'>
    <SlashCommand name='seek'>
  <SlashCommand name='loop_mode'>
 <SlashCommand name='loop_amount'>
     <SlashCommand name='remove'>
     <SlashCommand name='readd_songs'>
     <SlashCommand name='move'>
   <SlashCommand name='rotate'>
    <SlashCommand name='song_request_thread'>
     <SlashCommand name='nightcore'>
   <SlashCommand name='controller'>
   <SlashCommand name='add_dj'>
    <SlashCommand name='remove_dj'>
    <SlashCommand name='stop'>
    <SlashCommand name='queue'>
    <SlashCommand name='clear_queue'>
    <SlashCommand name='restrict_mode'>
   <SlashCommand name='247'>
  <SlashCommand name='change_node'>
  <SlashCommand name='player_settings'>
    <SlashCommand name='setup'>
    <SlashCommand name='reset'>
     <SlashCommand name='add_dj_role'>
  <SlashCommand name='remove_dj_role'>
    <SlashCommand name='change_skin'>
    <SlashCommand name='nodeinfo'>
     <SlashCommand name='rich_presence'>
    <UserCommand name='avatar'>
    <UserCommand name='Add DJ'>
    <MessageCommand name='add to queue'>

**Comment by BarboPT** [comment]
![imagem](https://github.com/zRitsu/disnake-LL-music-bot/assets/97259109/e63cae3d-f44e-48e8-b83c-b9c4fc72ce15)

**Comment by zRitsu** [comment]
Are you having any problems while using commands? by print and log it appears to be normal (once the commands are synchronized when restarting the bot, the commands are not synchronized if there is no change in the name/description in cmds, etc.)🤔
