### ISSUE TITLE
MULTIPLE PREFIXES WITH MULTIPLE TOKENS

### ISSUE THREAD

**Issue by cheeto5** [zRitsu/MuseHeart-MusicBot#35]
HOW TO DO MULTIPLE PREFIXES WITH MULTIPLE TOKENS?

**Comment by zRitsu** [comment]
This has not been implemented yet, all bots use the same prefix (with the possibility for member to set a personal prefix)

**Comment by cheeto5** [comment]
but you will do it?

**Comment by zRitsu** [comment]
A simple multi-prefix to be used by all bots is relatively easy to do, but a dedicated prefix for each bot would make using the multi-voice system very confusing.

**Comment by cheeto5** [comment]
so you can't do it?

**Comment by zRitsu** [comment]
At time: No.

Because I don't intend to undo the multi-voice function to leave all bots working with a different prefix between them (as it was originally).
