### ISSUE TITLE
Sobre a alteração de licença

### ISSUE THREAD

**Issue by Mirah3530** [zRitsu/MuseHeart-MusicBot#37]
Não é bem uma issue mas tenho uma dúvida a respeito da licença que foi alterada de MIT pra GPL2. Terei algum problema com o meu uso atual da source após essa alteração de licença? (Uso ela apenas pra rodar uns 4 bots privados no meu server).

**Comment by zRitsu** [comment]
Com o teu uso atual (vendo que você possui fork) não está infringindo nada da licença GPL-2 (pois n foi removido a unica informação exibida no code do bot que pode de alguma forma direcionar ao criador da source original que é o link da source exibida no comando about).

Embora eu não me importasse muito em manter a source com a licença MIT já que bots com foco em música é um caso complicado atualmente (até mesmo pra verificar) meio que deixei essa source pra qualquer 1 usar em um bot próprio sem depender muito dos slots de servers limitados dos meus bots principais (que não são verificadas).

Mas recentemente tive um certo problema que me fez cogitar em alterar pra uma licença um pouco mais restritiva devido a uma situação ocorrida algumas semanas atrás no qual o meu bot principal foi acusado de kibado ao enviar um dos meus bots pra uma botlist pequena (o motivo foi que outra pessoa usando um bot com essa source enviou o bot antes pra mesma botlist ou em alguma botlist parceira e o link de referência da source do comando about tinha sido removido desse bot) no qual eu fiquei como kibador msm eu sendo criador dessa source.

A licença GPL-2 vai servir pra desencorajar usuários que desejam divulgar bots usando essa source de remover créditos e obrigar a manter o code aberto (uma medida que pode servir pra provar que sou o criador original e evitar que meu bot seja acusado de kibado novamente).

Nota: Tinha conseguido provar pra pessoa que avaliou o meu bot e a mesma ja tinha pedido desculpas pelo ocorrido e tinha solicitado pra enviar o bot novamente (mas eu já estava desconfortável com a situação que simplesmente deixei de mão).
![image](https://github.com/zRitsu/MuseHeart-MusicBot/assets/74823568/99c55c42-6d37-4321-9fd2-ab68b6c5646f)

**Comment by zRitsu** [comment]
Com o teu uso atual (vendo que você possui fork) não está infringindo nada da licença GPL-2 (pois n foi removido a unica informação exibida no code do bot que pode de alguma forma direcionar ao criador da source original que é o link da source exibida no comando about) Edit: E mesmo que tivesse removido essa informação, em bot pra ser usado apenas em servers no qual o usuário é dono (ou que tenha perm de gerenciar o server) eu nem ligo muito pra isso.

Mas pra situações no qual o usuário deseja divulgar o bot pra ser adicionado publicamente (bot que esteja usando essa source) já é um é um caso diferente...

Embora eu não me importasse muito em manter a source com a licença MIT já que focar no crescimento de bots com foco em música é um caso complicado atualmente (até mesmo pra verificar) meio que deixei essa source com uma licença bem permissiva pra qualquer 1 usar em um bot próprio sem depender muito dos slots de servers limitados dos meus bots principais (que não são verificadas).

Mas recentemente tive um certo problema que me fez cogitar em alterar pra uma licença um pouco mais restritiva devido a uma situação ocorrida algumas semanas atrás no qual o meu bot principal foi acusado de kibado ao enviar um dos meus bots pra uma botlist pequena (o motivo foi que outra pessoa usando um bot com essa source enviou o bot antes pra mesma botlist ou em alguma botlist parceira e o link de referência da source do comando about tinha sido removido desse bot) no qual eu fiquei como kibador nessa história msm eu sendo criador dessa source.

A licença GPL-2 vai servir pra desencorajar usuários que desejam divulgar bots que estejam usando essa source (pra ser adicionado publicamente) de remover o link da source exibida no comando about e obrigar a manter o code aberto (Uma medida que pode servir pra provar que sou o criador da source em possíveis situações de meu bot ser acusado de kibado novamente embora eu não me importe muito que tenha vários bots públicos usando essa source desde que estejam seguindo as condições da licença [GPL-2](https://github.com/zRitsu/MuseHeart-MusicBot/blob/main/LICENSE)).

Nota: Tinha conseguido provar pra pessoa que avaliou o meu bot que eu era o criador original e a mesma ja tinha pedido desculpas pelo ocorrido e tinha solicitado pra enviar o bot novamente (mas eu já estava desconfortável com a situação que simplesmente deixei de mão).
![image](https://github.com/zRitsu/MuseHeart-MusicBot/assets/74823568/99c55c42-6d37-4321-9fd2-ab68b6c5646f)
